### PR TITLE
changed versions

### PR DESCRIPTION
**Pull request by NimG98**
Issue: https://github.com/OpenLiberty/guides-common/issues/419

pom.xml:
- junit-jupiter -> 5.6.2
- LMP -> 3.2
- MP -> 3.3

server.xml:
- mpHealth -> 2.2
- mpConfig -> 1.4
- mpRestClient ->1.4

### CODE REVIEW

**Comment by Bukama** [comment]
Yesterday 5.6.2 was released

**Comment by gkwan-ibm** [comment]
@NimG98 
-  [ ] change javaee 8.0.1 to jakarta.jakartaee-web-api 8.0

**Comment by NimG98** [comment]
tested guide end-to-end on lgdev, LGTM

**Comment by DannyS03** [comment]
- tested/verified on **qa**

**Pull request merged**
